# Landscape2 settings
#
# This settings file allows customizing some aspects of the landscape.
#
# Reference documentation: https://github.com/cncf/landscape2/blob/main/docs/config/settings.yml

foundation: CDIF

url: https://lanscape.cdif.org
#base_path: /cdif-landscape

colors:
  color1: "rgba(0, 107, 204, 1)"
  color2: "rgba(255, 0, 170, 1)"
  color3: "rgba(96, 149, 214, 1)"
  color4: "rgba(0, 42, 81, 0.7)"
  color5: "rgba(1, 107, 204, 0.7)"
  color6: "rgba(0, 42, 81, 0.7)"
  color7: "rgba(180, 219, 255, 1)"

description: Demo landscape for local development.

featured_items:
  - field: maturity
    options:
      - value: graduated
        order: 1
        label: Graduated

footer:
  links:
    #facebook: "https://www.facebook.com/CloudNativeComputingFoundation/"
    #flickr: "https://www.flickr.com/photos/143247548@N03/albums"
    github: "https://github.com/codata"
    homepage: "https://www.codata.org"
    #instagram: "https://www.instagram.com/humans.of.cloudnative/"
    linkedin: "https://www.linkedin.com/company/codata-isc-committee-on-data"
    #slack: "https://slack.cncf.io/"
    #twitch: "https://www.twitch.tv/cloudnativefdn"
    twitter: "https://x.com/CODATANews"
    #wechat: "https://www.cncf.io/wechat/"
    #youtube: "https://www.youtube.com/c/cloudnativefdn"
  logo: "logos/codata.svg"

grid_items_size: large

groups:
  - name: All
    categories:
      - Organizations
      - Tools
      - Standards
  - name: Tools
    categories:
      - Tools
  - name: Sample
    categories:
      - Category 1

header:
  links:
    github: "https://github.com/Cross-Domain-Interoperability-Framework/landscape"
  logo: "logos/cdif_300.png"

screenshot_width: 1500
